apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-day4
  name: nginx-deployment-day4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-day4
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-day4
    spec:
      containers:
      - image: nginx:1.19.2
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi
