apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {}

    http {
        server {
            listen 80;
            listen 4430 ssl;
            ssl_certificate /etc/nginx/tls/certificado.crt;
            ssl_certificate_key /etc/nginx/tls/chave-privada.key;

            location / {
                return 200 'Ol√° terraqueos e extraterrestres!\n';
                add_header Content-Type text/plain;
            }

        }
    }
